# Use the official Nginx image as the base
FROM nginx:alpine as runtime

# Remove the default Nginx HTML files
RUN rm -rf /usr/share/nginx/html/*

# Copy the contents of the 'wip-pages' directory to Nginx's html directory
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
